init 18:
    image dv laugh dress far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_laugh.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_laugh.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_laugh.png'))
    
    image dv laugh dress = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_laugh.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_laugh.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_laugh.png'))
    
    image dv normal dress far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_normal.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_normal.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_normal.png'))
    
    image dv normal dress = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_normal.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_normal.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_normal.png'))
    
    image dv smile dress far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_smile.png'))
    
    image dv smile dress = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv dress normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_smile.png'))

    image dv laugh sport = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_laugh.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_laugh.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_laugh.png'))
    
    image dv laugh sport far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_laugh.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_laugh.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_laugh.png'))
    
    image dv normal sport far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_normal.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_normal.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_normal.png'))
    
    image dv normal sport = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_normal.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_normal.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_normal.png'))
    
    image dv smile sport far = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/far/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport far.png', (0, 0), 'images/1080/sprites/far/dv/dv_4_smile.png'))
    
    image dv smile sport = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/dv/dv_4_body.png', (0, 0), 'scenario_alt/Pics/sprites/dv sport normal.png', (0, 0), 'images/1080/sprites/normal/dv/dv_4_smile.png'))
    
    image mi upset dress = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/mi/mi_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/mi dress normal.png', (0, 0), 'images/1080/sprites/normal/mi/mi_3_upset.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/mi/mi_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/mi dress normal.png', (0, 0), 'images/1080/sprites/normal/mi/mi_3_upset.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/mi/mi_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/mi dress normal.png', (0, 0), 'images/1080/sprites/normal/mi/mi_3_upset.png'))
    
    image mi normal dress = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/mi/mi_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/mi dress normal.png', (0, 0), 'images/1080/sprites/normal/mi/mi_3_normal.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/mi/mi_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/mi dress normal.png', (0, 0), 'images/1080/sprites/normal/mi/mi_3_normal.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/mi/mi_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/mi dress normal.png', (0, 0), 'images/1080/sprites/normal/mi/mi_3_normal.png'))
    
    image mi serious dress = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/mi/mi_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/mi dress normal.png', (0, 0), 'images/1080/sprites/normal/mi/mi_3_normal.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/mi/mi_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/mi dress normal.png', (0, 0), 'images/1080/sprites/normal/mi/mi_3_normal.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/mi/mi_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/mi dress normal.png', (0, 0), 'images/1080/sprites/normal/mi/mi_3_normal.png'))
    
    image sl cry dress = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/sl/sl_4_body.png', (0, 0), 'images/1080/sprites/normal/sl/sl_4_dress.png', (0, 0), 'scenario_alt/Pics/sprites/sl cry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/sl/sl_4_body.png', (0, 0), 'images/1080/sprites/normal/sl/sl_4_dress.png', (0, 0), 'scenario_alt/Pics/sprites/sl cry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/sl/sl_4_body.png', (0, 0), 'images/1080/sprites/normal/sl/sl_4_dress.png', (0, 0), 'scenario_alt/Pics/sprites/sl cry.png'))
   
    image sl cry pioneer = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/sl/sl_4_body.png', (0, 0), 'images/1080/sprites/normal/sl/sl_4_pioneer.png', (0, 0), 'scenario_alt/Pics/sprites/sl cry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/sl/sl_4_body.png', (0, 0), 'images/1080/sprites/normal/sl/sl_4_pioneer.png', (0, 0), 'scenario_alt/Pics/sprites/sl cry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/sl/sl_4_body.png', (0, 0), 'images/1080/sprites/normal/sl/sl_4_pioneer.png', (0, 0), 'scenario_alt/Pics/sprites/sl cry.png'))
    
    image un cry sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_cry.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_cry.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_cry.png'))

    image un surprise sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_surprise.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_surprise.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_surprise.png'))

    image un cry_smile sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_cry_smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_cry_smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_cry_smile.png'))
    
    image un sad sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_sad.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_sad.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_sad.png'))
    
    image un scared sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_scared.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_scared.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_scared.png'))

    image un shocked sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_shocked.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_shocked.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_2_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt.png', (0, 0), 'images/1080/sprites/normal/un/un_2_shocked.png'))
    
    image un angry2 sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_angry2.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_angry2.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_angry2.png'))

    image un grin sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_grin.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_grin.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_grin.png'))

    image un laugh sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080), (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_laugh.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_laugh.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_laugh.png'))
    
    image un rage sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_rage.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_rage.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_rage.png'))
    
    image un serious sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_serious.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_serious.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_serious.png'))

    image un smile3 sleep = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_smile3.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_smile3.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/1080/sprites/normal/un/un_3_body.png', (0, 0), 'scenario_alt/Pics/sprites/un sleep shirt2.png', (0, 0), 'images/1080/sprites/normal/un/un_3_smile3.png'))
    
    image slavya_ms = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/3500/sprites/full/sl/sl_1_body.png', (0, 0), 'images/3500/sprites/full/sl/sl_1_pioneer.png', (0, 0), 'images/3500/sprites/full/sl/sl_1_smile.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((1050, 1080),  (0, 0), 'images/3500/sprites/full/sl/sl_1_body.png', (0, 0), 'images/3500/sprites/full/sl/sl_1_pioneer.png', (0, 0), 'images/3500/sprites/full/sl/sl_1_smile.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((1050, 1080),  (0, 0), 'images/3500/sprites/full/sl/sl_1_body.png', (0, 0), 'images/3500/sprites/full/sl/sl_1_pioneer.png', (0, 0), 'images/3500/sprites/full/sl/sl_1_smile.png'))
    
    image cs grin = ConditionSwitch("persistent.sprite_time=='sunset'", im.MatrixColor(im.Composite((900, 1080),  (0, 0), 'images/1080/sprites/normal/cs/cs_1_body.png', (0, 0),  'scenario_alt/Pics/sprites/cs grin.png'), im.matrix.tint(0.94, 0.82, 1.0)), "persistent.sprite_time=='night'", im.MatrixColor(im.Composite((900, 1080),  (0, 0), 'images/1080/sprites/normal/cs/cs_1_body.png', (0, 0), 'scenario_alt/Pics/sprites/cs grin.png'), im.matrix.tint(0.63, 0.78, 0.82)), True, im.Composite((900, 1080),  (0, 0), 'images/1080/sprites/normal/cs/cs_1_body.png', (0, 0), 'scenario_alt/Pics/sprites/cs grin.png'))
    
    
#####################################################    
# Кошкоспрайты
#####################################################
    # neko
    image sl neko veryfar = ComposeSpriteSet('veryfar', 'sl/sl_neko.png')['veryfar']
    image dv neko veryfar = ComposeSpriteSet('veryfar', 'dv/dv_neko.png')['veryfar']
    image un neko veryfar = ComposeSpriteSet('veryfar', 'un/un_neko.png')['veryfar']
    image mi neko veryfar = ComposeSpriteSet('veryfar', 'mi/mi_neko.png')['veryfar']
    
    # sl
    image sl pioneer normal veryfar = ComposeSpriteSet('veryfar', 'sl/sl_1_body.png', 'sl/sl_1_pioneer.png', 'sl/sl_1_normal.png')['veryfar']
    image sl pioneer serious veryfar = ComposeSpriteSet('veryfar', 'sl/sl_1_body.png', 'sl/sl_1_pioneer.png', 'sl/sl_1_serious.png')['veryfar']
    image sl pioneer scared veryfar = ComposeSpriteSet('veryfar', 'sl/sl_4_body.png', 'sl/sl_4_pioneer.png', 'sl/sl_4_scared.png')['veryfar']   
    image sl pioneer surprise veryfar = ComposeSpriteSet('veryfar', 'sl/sl_3_body.png', 'sl/sl_3_pioneer.png', 'sl/sl_3_surprise.png')['veryfar']   
    
    # un
    image un pioneer normal veryfar = ComposeSpriteSet('veryfar', 'un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_normal.png')['veryfar']
    image un pioneer scared veryfar = ComposeSpriteSet('veryfar', 'un/un_2_body.png', 'un/un_2_pioneer.png', 'un/un_2_scared.png')['veryfar']
    image un pioneer shocked veryfar = ComposeSpriteSet('veryfar', 'un/un_2_body.png', 'un/un_2_pioneer.png', 'un/un_2_shocked.png')['veryfar']    
    image un pioneer serious veryfar = ComposeSpriteSet('veryfar', 'un/un_3_body.png', 'un/un_3_pioneer.png', 'un/un_3_serious.png')['veryfar']
    image un pioneer evilsmile veryfar = ComposeSpriteSet('veryfar', 'un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_evil_smile.png')['veryfar']
    image un pioneer shy veryfar = ComposeSpriteSet('veryfar', 'un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_shy.png')['veryfar']
    image un pioneer surprise veryfar = ComposeSpriteSet('veryfar', 'un/un_2_body.png', 'un/un_2_pioneer.png', 'un/un_2_surprise.png')['veryfar']

    # el
    image el pioneer slap = ComposeSpriteSet('normal', 'el/el_2_body.png', 'el/el_2_pioneer.png',  'el/el_slap.png')['normal']
    image el pioneer normal veryfar = ComposeSpriteSet('veryfar', 'el/el_1_body.png', 'el/el_1_pioneer.png',  'el/el_1_normal.png')['veryfar']
    image el pioneer scared veryfar = ComposeSpriteSet('veryfar', 'el/el_2_body.png', 'el/el_2_pioneer.png',  'el/el_2_scared.png')['veryfar']
    image el pioneer sad veryfar = ComposeSpriteSet('veryfar', 'el/el_2_body.png', 'el/el_2_pioneer.png',  'el/el_2_sad.png')['veryfar']
    image el pioneer surprise veryfar = ComposeSpriteSet('veryfar', 'el/el_2_body.png', 'el/el_2_pioneer.png',  'el/el_2_surprise.png')['veryfar']
    
    # sh
    image sh pioneer rage veryfar = ComposeSpriteSet('veryfar', 'sh/sh_2_body.png', 'sh/sh_2_rage.png')['veryfar']
    image sh pioneer scared veryfar = ComposeSpriteSet('veryfar', 'sh/sh_1_body.png', 'sh/sh_1_scared.png')['veryfar']
    
    $ _sh_angry_bar = ComposeSpriteSet(('veryfar', 'far','normal','close'), 'sh/sh_angry_bar.png')
    $ _sh_angry_bar3 = ComposeSpriteSet(('normal', 'far', 'veryfar'),  'sh/sh_angry_bar3.png')
    image sh angry bar close        = _sh_angry_bar['close']
    image sh angry bar              = _sh_angry_bar['normal']
    image sh angry bar far          = _sh_angry_bar['far']
    image sh angry bar veryfar      = _sh_angry_bar['veryfar']
    image sh angry bar2 close       = ComposeSpriteSet( 'close',  'sh/sh_angry_bar2.png')['close']
    image sh mad bar2 close         = ComposeSpriteSet( 'close',  'sh/sh_angry_bar2.png', 'sh/sh_mad_smile.png')['close']
    image sh angry bar3             = _sh_angry_bar3['normal']
    image sh angry bar3 far         = _sh_angry_bar3['far']
    image sh angry bar3 veryfar     = _sh_angry_bar3['veryfar']

    # mt
    image mt pioneer angry veryfar = ComposeSpriteSet('veryfar',  'mt/mt_2_body.png', 'mt/mt_2_pioneer.png',  'mt/mt_2_angry.png')['veryfar']
    image mt pioneer normal veryfar = ComposeSpriteSet('veryfar', 'mt/mt_1_body.png',  'mt/mt_1_pioneer.png', 'mt/mt_1_normal.png')['veryfar']
    image mt pioneer scared3 veryfar = ComposeSpriteSet('veryfar', 'mt/mt_3_body.png',  'mt/mt_3_pioneer.png', 'mt/mt_3_scared3.png')['veryfar']
    image mt pioneer surprise veryfar = ComposeSpriteSet('veryfar', 'mt/mt_1_body.png',  'mt/mt_1_pioneer.png', 'mt/mt_1_surprise.png')['veryfar']
    image mt scared3 panama pioneer = ComposeSpriteSet('normal', 'mt/mt_3_body.png',  'mt/mt_3_pioneer.png', 'mt/mt_3_scared3.png', 'mt/mt_3_panama.png')['normal']
    #image mt surprise panama pioneer = ComposeSpriteSet('normal', 'mt/mt_3_body.png',  'mt/mt_3_pioneer.png', 'mt/mt_1_surprise.png', 'mt/mt_3_panama.png')['normal']

    # cs 
    $ _cs_normal2 = ComposeSpriteSet(('normal', 'close', 'far'), 'cs/cs_2_body.png', 'cs/cs_1_normal.png')
    $ _cs_smile2 = ComposeSpriteSet( ('normal', 'close', 'far'), 'cs/cs_2_body.png',  'cs/cs_1_smile.png')
    $ _cs_badgirl2 = ComposeSpriteSet(('close', 'normal'), 'cs/cs_2_body.png', 'cs/cs_2_badgirl.png')
    image cs normal2 close    = _cs_normal2['close']
    image cs normal2          = _cs_normal2['normal']
    image cs normal2 far      = _cs_normal2['far']
    image cs smile2 close    = _cs_smile2['close']
    image cs smile2          = _cs_smile2['normal']
    image cs smile2 far      = _cs_smile2['far']
    image cs shy2 close    = ComposeSpriteSet( 'close', 'cs/cs_2_body.png', 'cs/cs_1_shy.png')['close']
    image cs badgirl2 close    = _cs_badgirl2['close']
    image cs badgirl2          = _cs_badgirl2['normal']
    image cs badgirl2 glasses    = ComposeSpriteSet('normal', 'cs/cs_1_body.png', 'cs/cs_1_glasses.png', 'cs/cs_2_badgirl.png')['normal']
    